version: '3.3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=easyweb
      - MYSQL_USER=aharon
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3307:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: {}